AllCops:
  Exclude:
    - 'db/**/*'

Style/StringLiterals:
  EnforcedStyle: double_quotes
  AutoCorrect: true

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/HashAlignment:
  EnforcedColonStyle: table

