#!/bin/sh

# script/server: Launch the application and any extra required processes
#                locally.

# ensure everything in the app is up to date.
script/update

test -z "$RAILS_ENV" &&
  RAILS_ENV='development'

# boot the app and any other necessary processes.
bundle exec rails s

